

MODEL:
  FEATURE_DIM: 32 # Feature dim for every vertex


INPUT:
  SIZE_RAW: [800,800] # Size of the original image
  SIZE_TRAIN: [600,600] # Size of the image during training
  SIZE_TEST: [600,600] # Size of the image during test
  NEAR_FAR_SIZE: [0.05, 0.7, 1] # Size of the image during test
  LAYER_NUM: 6 # depth peeling layers
  USE_RGB: False # use RGB to initialize, always False

DATASETS:
  TRAIN: "./datasets/Hair2" # datasets path
  FRAME_NUM: 1 # Keep the value unchanged
  MASK: True # Keep the value unchanged
  CENTER: [400,400] # focus center for each real camera, [y1,x1,y2,x2,y3,x3,...]. Different for scenes
  SHIFT: 10 # Translation range in data augmentation: [-SHIFT,SHIFT]
  MAXRATION: 0.5 # Scale range in data augmentation: [1,1+MAXRATION]
  ROTATION: 0.0 # Rotation range in data augmentation: [-ROTATION,ROTATION]


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  WARMUP_FACTOR: 0.333 # do crop
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

WEIGHTS: # Blend weights, keep the value unchanged
  REFINE_WEIGHTS: [0.5, 0.5, 0.25, 0.75]
  RENDER_WEIGHTS: [0.5, 0.12, 0.12, 0.08, 0.08, 0.08, 0.02]
  COLOR_THR: 8000
  DEPTH_THR: 0.05

OUTPUT_DIR: "./output" # checkpoint and render results output dir
BACKGROUND_GRAY: 60 # background color when rendering
LOAD_EPOCH: 205 # checkpoint to load when train/render/refine
RESUME: True # if resume when train