

MODEL:
  FEATURE_DIM: 32


INPUT:
  SIZE_RAW: [1920, 1080]
  SIZE_TRAIN: [768,432]
  SIZE_TEST: [768,432]
  NEAR_FAR_SIZE: [5.0, 18.0, 1]
  LAYER_NUM: 1
  USE_RGB: False

DATASETS:
  TRAIN: "./datasets/Wolf"
  FRAME_NUM: 1
  MASK: True
  CENTER: [540,960]
  SHIFT: 10
  MAXRATION: 0.5
  ROTATION: 0.0


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

TEST:
  IMS_PER_BATCH: 256

WEIGHTS:
  REFINE_WEIGHTS: [0.5, 0.5, 0.25, 0.75]
  RENDER_WEIGHTS: [0.25, 0.2, 0.2, 0.15, 0.1, 0.08, 0.02]
  COLOR_THR: 8000

OUTPUT_DIR: "./output"
BACKGROUND_GRAY: 255
LOAD_EPOCH: 0
RESUME: False
